# Generated by Django 3.2.5 on 2021-08-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='this_gender',
            field=models.TextField(max_length=10),
        ),
    ]
