# Generated by Django 3.2.5 on 2021-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_gender_this_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='this_gender',
            field=models.CharField(max_length=10),
        ),
    ]
