# Generated by Django 3.2.5 on 2021-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='latest_bid',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
