# Generated by Django 3.2.5 on 2021-09-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watched_listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watching',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watched_listing', to='auctions.listing'),
        ),
    ]
